
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - 9002:80
  database:
    image: 'mysql:8'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3309:3306"
    volumes:
      - "database_volume:/var/lib/mysql"
volumes:
  database_volume:






